# filename: ciwa/config/settings.yaml

# YAML Configuration for CIwA setup will go here.
# Example structure:

process:
  name: "CIwA Demo Process"
  version: "0.1.0"
  description: "A demo process for CIwA"
  owners:
    - name: "Default Owner"
      email: "evan@cip.org"
  default_session_settings:
    max_subs_per_topic: 5 # max submissions from each participant per topic
    max_concurrent: 100 # max concurrent requests for submissions
    default_topic_settings:
      voting_strategy:
        type: "RankingComparison"
    participants:
      - type: "LLMAgentParticipant"
        model: "gpt-3.5-turbo"
        temperature: 0.5
        cache_seed: null
        prompt_template: "default_template"
      - type: "LLMAgentParticipant"
        model: "gpt-3.5-turbo"
        prompt_template: "alternative_template"
        temperature: 0.4
        cache_seed: null
      - type: "LLMAgentParticipant"
        model: "gpt-3.5-turbo"
        prompt_template: "alternative_template"
        temperature: 0.3
        cache_seed: null
      - type: "LLMAgentParticipant"
        model: "gpt-3.5-turbo"
        prompt_template: "alternative_template"
        temperature: 0.2
        cache_seed: null
      - type: "LLMAgentParticipant"
        model: "gpt-3.5-turbo"
        prompt_template: "alternative_template"
        temperature: 0.6
        cache_seed: null
      - type: "LLMAgentParticipant"
        model: "gpt-3.5-turbo"
        prompt_template: "alternative_template"
        temperature: 0.7
        cache_seed: null
      - type: "LLMAgentParticipant"
        model: "gpt-3.5-turbo"
        prompt_template: "alternative_template"
        temperature: 0.8
        cache_seed: null
  sessions:
    - name: "Demo Session"
      description: "A demo session for CIwA"
      next_session: "Demo Session" # re-run the same session
      default_topic_settings:
        voting_strategy:
          type: "YesNoLabeling"
      topics:
        - title: "What is a good topic to test this on?"
          description: "Give a submission for what would be a good topic to test this on."
        - title: "What are 3 topics that would be good to test this on?"
          description: "Give a submission with 3 different topics, enumerated A. B. C. for what would be good to test this on."
          voting_strategy:
            type: "EnumLabeling" 
            enum_values: ["A", "B", "C"]
        - title: "What is a good starting move for Chess?"
          description: "Give a submission for what would be a good starting move for Chess, in Standard Algebraic Notation (SAN)."
          voting_strategy:
            type: "ScoreComparison"
            start_value: 1
            end_value: 10
            increment_value: 1
