# filename: ciwa/config/settings.yaml

# YAML Configuration for CIwA setup will go here.
# Example structure:

process:
  name: "CIwA Demo Process"
  version: "0.1.0"
  description: "A demo process for CIwA"
  owners:
    - name: "Default Owner"
      email: "evan@cip.org"
  default_session_settings:
    max_subs_per_topic: 2 # max submissions from each participant per topic
    default_topic_settings:
      voting_strategy:
        type: "YesNoLabeling"
      max_submissions: 10 # max submissions total for the topic TODO: remove this once verified that we aren't using this
    participants:
      - type: "ConversableAgentParticipant"
        model: "gpt-3.5"
        temperature: 0.9
        prompt_template: "default_template"
      - type: "ConversableAgentParticipant"
        model: "gpt-3.5"
        prompt_template: "alternative_template"
        temperature: 0.9
  sessions:
    - name: "Demo Session"
      description: "A demo session for CIwA"
      next_session: "Demo Session" # re-run the same session
      default_topic_settings:
        voting_strategy:
          type: "YesNoLabeling"
        max_submissions: 2
      topics:
        - title: "What is a good topic to test this on?"
          description: "Give a submission for what would be a good topic to test this on."
        - title: "What are 3 topics that would be good to test this on?"
          description: "Give a submission with 3 different topics, enumerated A. B. C. for what would be good to test this on."
          voting_strategy:
            type: "EnumLabeling" 
            enum_values: ["A", "B", "C"]
          max_submissions: 2
