# config/settings.yaml

# YAML Configuration for CIwA setup will go here.
# Example structure:

process:
  name: "CIwA Demo Process"
  version: "0.1.0"
  description: "A demo process for CIwA"
  owners:
    - name: "Default Owner"
      email: "evan@cip.org"
  default_session_settings:
    submissions_per_participant_per_topic: 2 # max submissions from each participant per topic
    max_concurrent: 100 # max concurrent requests for submissions
    batch_submissions: true # ask participants for all submissions at once rather than one at a time
    default_topic_settings:
      voting_method:
        type: "RankingCompare"
    participants:
      - type: "ConversableAgentParticipant"
        model: "gpt-3.5-turbo"
        temperature: 0.6
        cache_seed: null
      - type: "ConversableAgentParticipant"
        model: "gpt-4-0125-preview"
        temperature: 0.6
        cache_seed: null
      - type: "ConversableAgentParticipant"
        model: "claude-2.1"
        temperature: 0.6
        cache_seed: null
      - type: "ConversableAgentParticipant"
        model: "claude-3-5-sonnet-20240620"
        temperature: 0.6
        cache_seed: null
      - type: "ConversableAgentParticipant"
        model: "gemini-1.0-pro"
        temperature: 0.6
        cache_seed: null
      - type: "ConversableAgentParticipant"
        model: "mistral-large-latest"
        temperature: 0.6
        cache_seed: null
  sessions:
    - name: "Demo Session"
      description: "A demo session for CIwA"
      next_session: "Demo Session" # re-run the same session
      default_topic_settings:
        voting_method:
          type: "EnumLabel"
      topics:
        - title: "What are possible future outcomes from AGI that people might like?"
          description: "Describe a realistic future outcome from AGI that is beneficial for humanity generally."
          voting_method:
            type: "RankingCompare"
